#!/usr/bin/with-contenv bash

# starting inotify to watch /config/ddclient.conf and restart ddclient if changed.
while inotifywait -e modify /config/ddclient.conf; do
	cp /config/ddclient.conf /ddclient.conf
	chown abc:abc /ddclient.conf
	chmod 600 /ddclient.conf
	s6-svc -h /var/run/s6/services/ddclient
	echo "ddclient has been restarted"
done
