#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /run/ddclient-cache \
    /run/ddclient

# copy default config if not present in /config
if [[ ! -e /config/ddclient.conf ]]; then
    cp /defaults/ddclient.conf /config
fi

# permissions
lsiown -R abc:abc \
    /config \
    /run/ddclient \
    /run/ddclient-cache

chmod 700 \
    /config \
    /run/ddclient-cache

chmod 600 \
    /config/*
