#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /var/cache/ddclient \
    /var/run/ddclient

# copy default config if not present in /config
if [[ ! -e /config/ddclient.conf ]]; then
    cp /defaults/ddclient.conf /config
fi

# copy config from /config to root
cp /config/ddclient.conf /ddclient.conf

# permissions
lsiown -R abc:abc \
    /config \
    /var/cache/ddclient \
    /var/run/ddclient \
    /ddclient.conf

chmod 700 /config
chmod 600 \
    /config/* \
    /ddclient.conf
